_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 50
                - 55
            "2":
                - 1
                - 50
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": darwin-arm64
params:
    value:
        dropout_rate: 0.5
        ff_hidden_dim: 256
        num_fc_layers: 2
        num_filters1: 32
        num_filters2: 64
        num_filters3: 128
